### PR TITLE
Adding aks logging

### PR DESCRIPTION
**Pull request by voojoe**
### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec](https://github.com/inspec/inspec-azure/CONTRIBUTING.MD) document before submitting.
Adding checks for enabled and disabled logging types in the AKS Cluster resource.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant
#305 

### Check List

- [ ] New functionality includes tests
- [✓] All tests pass
- [✓] `rake lint` passes
- [✓] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by voojoe** [comment]
Hi @omerdemirok 

Thanks for the reply, all sounds like good suggestions, I'll make these changes and push them shortly.

**Comment by voojoe** [comment]
Hi @omerdemirok 

I've made some changes, which should hopefully fit better with the new backend.

Thanks

**Review by omerdemirok — CHANGES_REQUESTED** [review]
Hi, @voojoe.
Thanks for the quick update!
Since these are static properties of the resource, we should add them to the [doc file](https://github.com/voojoe/inspec-azure/blob/adding-aks-logging/docs/resources/azure_aks_cluster.md#properties) to let users know about it.

**Comment by voojoe** [comment]
> Hi, @voojoe.
> Thanks for the quick update!
> Since these are static properties of the resource, we should add them to the [doc file](https://github.com/voojoe/inspec-azure/blob/adding-aks-logging/docs/resources/azure_aks_cluster.md#properties) to let users know about it.

Hi, 

I've just added these into the docs now

Thanks

**Review by omerdemirok — APPROVED** [review]
Thanks for your contribution @voojoe!

**Review by skpaterson — APPROVED** [review]
Thanks for this contribution @voojoe !

**Pull request merged**
