### PR TITLE
Account Storage Resource Fix

### PR DESCRIPTION
**Pull request by sa-progress**
Obvious fix; these changes are the result of automation not creative thinking.

Signed-off-by: sa-progress <samir.anand@progress.com>

### Description
This PR is fix for account storage : filter name - **has_recently_generated_access_key**

1. Account should regenerate new key if greater than 90 days .
2. Regret key regenerate not required if account is newly created -- this case was failing. Filter was looking for regenerate call in all the cases.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by sathish-progress** [comment]
This PR does not do what is says actually ..

**Comment by sa-progress** [comment]
> This PR does not do what is says actually ..

This PR is fix for account storage .For one use case when account storage is new, for one filter It was failing .
Use case 1>. Account should regenerate new key if greater than 90 days .
Use case2> Regret keygen not required if account is newly created -- this case was failing.

**Comment by sa-progress** [comment]
> > This PR does not do what is says actually ..
> 
> This PR is fix for account storage .For one use case when account storage is new, for one filter It was failing .
> Use case 1>. Account should regenerate new key if greater than 90 days .
> Use case2> Regret keygen not required if account is newly created -- this case was failing.

Filter Name : has_recently_generated_access_key

**Comment by sathish-progress** [comment]
No but this PR summary says about bumping version of chef expeditor .. Could you update the PR summary and details ?

**Comment by sathish-progress** [comment]
@sa-progress should we update the docs for this with this change?

**Review by sathish-progress — APPROVED** [review]
LGTM

**Pull request merged**
