### PR TITLE
Support azure synapse notebooks

### PR DESCRIPTION
**Pull request by sathish-progress**
### Description

Support Azure Synapse Workspace notebook(s)

### Check List

- [X] New functionality includes tests
- [X] All tests pass
- [X] `rake lint` passes
- [X] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Review by sa-progress — COMMENTED** [review]
Might include language_info from metadata ,That could be the filter condition and kernelspec as well.

**Review by sa-progress — COMMENTED** [review]
Everything else looks good to go.

**Comment by sathish-progress** [comment]
> Might include language_info from metadata ,That could be the filter condition and kernelspec as well.

yeah we can filter today using this way 

```
azure_synapse_notebooks(endpoint: 'https://analytics.dev.azuresynapse.net').where { properties.select{|prop| prop.metadata.language_info.name == 'Python' }} }
```

but if there is a requirement from somebody to get this on flat, we can do further changes

**Comment by sa-progress** [comment]
> > Might include language_info from metadata ,That could be the filter condition and kernelspec as well.
> 
> yeah we can filter today using this way
> 
> ```
> azure_synapse_notebooks(endpoint: 'https://analytics.dev.azuresynapse.net').where { properties.select{|prop| prop.metadata.language_info.name == 'Python' }} }
> ```
> 
> but if there is a requirement from somebody to get this on flat, we can do further changes

Great .Every thing looks good.

**Review by sa-progress — APPROVED** [review]

**Review by IanMadd — APPROVED** [review]

**Pull request merged**
