### PR TITLE
Feature/iothub event hubs

### PR DESCRIPTION
**Pull request by MRushtonScratch**
### Description

Please describe what this change achieves. Ensure you have read the [Contributing to InSpec](https://github.com/inspec/inspec-azure/CONTRIBUTING.MD) document before submitting.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### Notes
I have included an example attributes file, that I used in order to get the majority of tests to pass, however some additional properties are required that I was unable to determine from the Azure resources that were provisioned by terraform.  If you could provide me an attributes that works for all existing resources then I can validate and be sure that all of the existing functionality has not been affected by this PR.

### CODE REVIEW

**Comment by MRushtonScratch** [comment]
Hi @r-fennell are there other contributors that are able to review this PR?

**Comment by davymcaleer** [comment]
@MRushtonScratch - aiming to get one of the team onto this PR in the next 2 weeks

**Comment by MRushtonScratch** [comment]
Bump ^^

**Comment by MRushtonScratch** [comment]
This PR is no longer required, functionality  was included in another PR in relation to CosmosDb

**Pull request closed without merging**
